sudo: false
language: node_js
node_js:
  - '10'
install: npm install
script:
  # - npm run lint
  # - npm test
  - npm run build
notifications:
  email: false
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   keep-history: true
#   local_dir: build
#   target-branch: gh-pages
#   on:
#     branch: development
cache:
  directories:
  - node_modules